# Makefile for tcp apps

all:
	$(MAKE) -C httpapp/ all
	$(MAKE) -C mhttping/ all

install:
	$(MAKE) -C httpapp/ install
	$(MAKE) -C mhttping/ install

clean:
	$(MAKE) -C httpapp/ clean
	$(MAKE) -C mhttping/ clean
